### ISSUE TITLE
Mask power spectrum normalisation

### ISSUE THREAD

**Issue by robinupham** [CosmoLike/CosmoCov#7]
Hi,

I think there's a problem with the mask power spectrum normalisation in the [`C_survey_window` function in `covariances_3D.c`](https://github.com/CosmoLike/CosmoCov/blob/a8efdc8a40571b2b2f8ca5c545e7af0d129ece88/cosmolike_core/theory/covariances_3D.c#L253). 
I assume that the intention is to divide all Cl by the l=0 Cl, but currently it seems that the l=0 Cl is divided by itself first, so all l > 0 Cl are just divided by 1.

I'd be happy to submit a fix for this - just let me know. I've found this code extremely useful, so many thanks for making it public.

Cheers,
Robin

**Comment by xfangcosmo** [comment]
Hi Robin, thank you for pointing that out. I will fix this now. (now fixed)
